apiVersion: v1
kind: Service
metadata:
  name: backend
spec:
  selector:
    app: backend
  ports:
    - port: {{ .Values.backend.service.port }}   # External port (8083)
      targetPort: 8080                           # Internal container port
  type: {{ .Values.backend.service.type }}
