apiVersion: v1
kind: Service
metadata:
  name: frontend
spec:
  selector:
    app: frontend
  type: {{ .Values.frontend.service.type | default "ClusterIP" }}
  ports:
    - port: 3000
      targetPort: {{ .Values.frontend.service.port }}
