replicaCount: 1
frontend:
  image:
    repository: ghcr.io/phanminhtri667/fullstack-frontend
    tag: a73893a503aa433b89e08a11f4fd3d182882657c
    pullPolicy: IfNotPresent
  service:
    type: ClusterIP
    port: 3000
    apiUrl: /api
backend:
  image:
    repository: ghcr.io/phanminhtri667/fullstack-backend
    tag: a73893a503aa433b89e08a11f4fd3d182882657c
    pullPolicy: IfNotPresent
  service:
    type: ClusterIP
    port: 8081
database:
  image:
    repository: ghcr.io/phanminhtri667/fullstack-database
    tag: a73893a503aa433b89e08a11f4fd3d182882657c
    pullPolicy: IfNotPresent
  service:
    name: mariadb
    port: 3306
  rootPassword: root
  database: fullstack
imagePullSecrets:
  - name: github-registry-secret
nameOverride: ""
fullnameOverride: ""
serviceAccount:
  create: true
  automount: true
  annotations: {}
  name: ""
podAnnotations: {}
podLabels: {}
podSecurityContext: {}
securityContext: {}
service:
  type: ClusterIP
  port: 8085
ingress:
  enabled: true
  className: nginx
  annotations:
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/rewrite-target: /api/$2
  hosts:
    - host: devops.tri.com
      paths:
        - path: /api(/|$)(.*)
          pathType: Prefix
          backend:
            serviceName: backend
            servicePort: 8081
        - path: /()(.*)
          pathType: Prefix
          backend:
            serviceName: frontend
            servicePort: 3000
  tls: []
resources: {}
livenessProbe:
  httpGet:
    path: /
    port: http
readinessProbe:
  httpGet:
    path: /
    port: http
autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
volumes: []
volumeMounts: []
nodeSelector: {}
tolerations: []
affinity: {}
