replicaCount: 1

frontend:
  image:
    repository: ghcr.io/phanminhtri667/fullstack-frontend
    tag: 76e29bc4766a425466dfb34cdbd2d427b59733cb
    pullPolicy: IfNotPresent
  service:
    type: ClusterIP
    port: 80
    apiUrl: /api

backend:
  image:
    repository: ghcr.io/phanminhtri667/fullstack-backend
    tag: 76e29bc4766a425466dfb34cdbd2d427b59733cb
    pullPolicy: IfNotPresent
  service:
    type: ClusterIP
    port: 8083

database:
  image:
    repository: ghcr.io/phanminhtri667/fullstack-database
    tag: 76e29bc4766a425466dfb34cdbd2d427b59733cb
    pullPolicy: IfNotPresent
  service:
    name: mariadb
    port: 3306
  rootPassword: root
  database: fullstack

imagePullSecrets:
  - name: github-registry-secret

nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  automount: true
  annotations: {}
  name: ""

podAnnotations: {}
podLabels: {}
podSecurityContext: {}
securityContext: {}

service:
  type: ClusterIP
  port: 8085

ingress:
  enabled: true
  className: nginx
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1
  hosts:
    - host: devops.tri.com
      paths:
        - path: /?(.*)
          pathType: Prefix
          backend:
            serviceName: frontend
            servicePort: 80
        - path: /api/?(.*)
          pathType: Prefix
          backend:
            serviceName: backend
            servicePort: 8083
  tls: []

resources: {}

livenessProbe:
  httpGet:
    path: /
    port: http
readinessProbe:
  httpGet:
    path: /
    port: http

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80

volumes: []
volumeMounts: []

nodeSelector: {}
tolerations: []
affinity: {}
